//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_tarea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public int IdConsulta { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Tipo { get; set; }
        public string Ciudad { get; set; }
        public string Usuario { get; set; }
        public string Consulta { get; set; }
    }

    public enum Tipo
    {
        Queja,
        Felicitacion,
        Consulta
    }
}
